# Generated by Django 4.0 on 2021-12-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('genericmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.genericmodels')),
                ('total', models.IntegerField(max_length=5, null=True)),
                ('discount', models.IntegerField(max_length=5, null=True)),
                ('shipping_fee', models.IntegerField(max_length=5, null=True)),
                ('tax', models.IntegerField(max_length=5, null=True)),
                ('grand_total', models.IntegerField(max_length=10, null=True)),
                ('product_size', models.IntegerField(default=0)),
            ],
            bases=('Buyer.genericmodels',),
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('genericmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.genericmodels')),
                ('token', models.CharField(max_length=100, null=True)),
                ('cardName', models.CharField(max_length=100, null=True)),
                ('cardNumber', models.BigIntegerField(max_length=100, null=True)),
                ('expiryDate', models.DateField(null=True)),
                ('cvcNum', models.IntegerField(max_length=10, null=True)),
            ],
            bases=('Buyer.genericmodels',),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('genericmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.genericmodels')),
                ('product_size', models.IntegerField(default=0)),
                ('number_of_tickets', models.IntegerField(default=1)),
            ],
            bases=('Buyer.genericmodels',),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('genericmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.genericmodels')),
                ('charge_id', models.CharField(max_length=100)),
            ],
            bases=('Buyer.genericmodels',),
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('genericmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.genericmodels')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
            bases=('Buyer.genericmodels',),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('usermodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Buyer.usermodels')),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=150)),
            ],
            bases=('Buyer.usermodels',),
        ),
        migrations.CreateModel(
            name='BuyerCard',
            fields=[
                ('cardmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.cardmodel')),
            ],
            bases=('Buyer.cardmodel',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Buyer.cartmodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('Buyer.cartmodel',),
        ),
    ]
